In [1]:
import pandas as pd
import numpy as np

headers = ["age", "workclass", "fnlwgt", "education",
           "education_num", "marriage_status", "occupation", "relationship",
           "race", "sex", "capital_gain", "capital_loss", "hours_per_week",
           "native_country",">50"]

df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data",
                  header=None,names=headers, na_values=" ?" )

In [ ]:
df.head()

In [ ]:
df.dtypes

In [2]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

,workclass,education,marriage_status,occupation,relationship,race,sex,native_country,>50
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States,<=50K
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,<=50K
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,<=50K
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,<=50K
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,<=50K

In [4]:
obj_df[obj_df.isnull().any(axis=1)]

,workclass,education,marriage_status,occupation,relationship,race,sex,native_country,>50
14,Private,Assoc-voc,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,NaN,>50K
27,NaN,Some-college,Married-civ-spouse,NaN,Husband,Asian-Pac-Islander,Male,South,>50K
38,Private,Some-college,Married-civ-spouse,Sales,Husband,White,Male,NaN,>50K
51,Private,HS-grad,Never-married,Other-service,Own-child,White,Female,NaN,<=50K
61,NaN,7th-8th,Married-spouse-absent,NaN,Not-in-family,White,Male,NaN,<=50K
69,NaN,Some-college,Never-married,NaN,Own-child,White,Male,United-States,<=50K
77,NaN,10th,Married-civ-spouse,NaN,Husband,White,Male,United-States,<=50K
93,Private,HS-grad,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,NaN,<=50K
106,NaN,10th,Never-married,NaN,Own-child,White,Female,United-States,<=50K
128,NaN,HS-grad,Married-civ-spouse,NaN,Husband,White,Male,United-States,<=50K
149,NaN,Some-college,Divorced,NaN,Not-in-family,White,Female,United-States,<=50K
154,NaN,HS-grad,Divorced,NaN,Not-in-family,White,Male,United-States,>50K
160,NaN,1st-4th,Divorced,NaN,Not-in-family,White,Female,United-States,<=50K
187,NaN,Bachelors,Divorced,NaN,Not-in-family,White,Female,United-States,<=50K
201,NaN,HS-grad,Never-married,NaN,Own-child,White,Male,Italy,<=50K
221,NaN,1st-4th,Divorced,NaN,Not-in-family,White,Male,United-States,<=50K
226,NaN,10th,Divorced,NaN,Not-in-family,Amer-Indian-Eskimo,Female,United-States,<=50K
243,NaN,Some-college,Never-married,NaN,Own-child,White,Male,United-States,<=50K
245,Private,HS-grad,Married-civ-spouse,Adm-clerical,Husband,White,Male,NaN,<=50K
249,Private,HS-grad,Married-civ-spouse,Adm-clerical,Husband,White,Male,NaN,<=50K
266,NaN,Some-college,Never-married,NaN,Own-child,White,Male,Canada,<=50K
297,NaN,Masters,Married-civ-spouse,NaN,Wife,Asian-Pac-Islander,Female,NaN,<=50K
312,NaN,Some-college,Never-married,NaN,Own-child,Black,Female,United-States,<=50K
326,NaN,Assoc-voc,Never-married,NaN,Own-child,Black,Female,United-States,<=50K
346,NaN,11th,Married-civ-spouse,NaN,Husband,White,Male,United-States,<=50K
347,NaN,Assoc-voc,Divorced,NaN,Unmarried,White,Female,United-States,<=50K
354,NaN,Bachelors,Married-civ-spouse,NaN,Husband,White,Male,United-States,>50K
393,State-gov,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,>50K
397,NaN,HS-grad,Never-married,NaN,Other-relative,White,Female,United-States,<=50K
408,NaN,Some-college,Married-civ-spouse,NaN,Wife,White,Female,United-States,>50K
...,...,...,...,...,...,...,...,...,...
32189,NaN,HS-grad,Married-civ-spouse,NaN,Wife,White,Female,United-States,<=50K
32201,NaN,HS-grad,Married-civ-spouse,NaN,Wife,White,Female,United-States,<=50K
32206,NaN,5th-6th,Widowed,NaN,Not-in-family,White,Female,United-States,<=50K
32213,Private,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Female,NaN,<=50K
32232,Private,Some-college,Never-married,Adm-clerical,Not-in-family,Other,Male,NaN,<=50K
32254,Private,Some-college,Married-civ-spouse,Other-service,Husband,Asian-Pac-Islander,Male,NaN,>50K
32275,NaN,Some-college,Never-married,NaN,Own-child,White,Female,United-States,<=50K
32291,NaN,Some-college,Never-married,NaN,Not-in-family,Black,Female,United-States,<=50K
32304,Never-worked,HS-grad,Married-civ-spouse,NaN,Wife,Black,Female,United-States,<=50K
32307,Self-emp-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,NaN,>50K
32310,NaN,Some-college,Never-married,NaN,Own-child,White,Male,United-States,<=50K
32314,Never-worked,Some-college,Never-married,NaN,Own-child,White,Male,United-States,<=50K
32317,NaN,Some-college,Divorced,NaN,Not-in-family,White,Female,United-States,<=50K
32335,NaN,11th,Never-married,NaN,Own-child,White,Female,United-States,<=50K
32343,NaN,HS-grad,Widowed,NaN,Unmarried,White,Female,United-States,<=50K
32413,Private,5th-6th,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,NaN,<=50K
32426,NaN,HS-grad,Never-married,NaN,Own-child,White,Male,United-States,<=50K
32449,Self-emp-inc,Masters,Married-civ-spouse,Sales,Husband,White,Male,NaN,>50K
32469,Self-emp-inc,Doctorate,Never-married,Prof-specialty,Not-in-family,White,Female,NaN,<=50K
32477,NaN,12th,Divorced,NaN,Other-relative,Black,Male,United-States,<=50K
32490,NaN,9th,Divorced,NaN,Not-in-family,Black,Male,United-States,<=50K
32492,Self-emp-not-inc,HS-grad,Divorced,Sales,Own-child,White,Male,NaN,<=50K
32494,NaN,HS-grad,Never-married,NaN,Not-in-family,White,Male,United-States,<=50K
32510,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,>50K
32525,NaN,Assoc-voc,Divorced,NaN,Unmarried,White,Female,NaN,<=50K
32530,NaN,Bachelors,Married-civ-spouse,NaN,Wife,White,Female,United-States,>50K
32531,NaN,Bachelors,Never-married,NaN,Not-in-family,Asian-Pac-Islander,Female,United-States,<=50K
32539,NaN,Doctorate,Married-civ-spouse,NaN,Husband,White,Male,United-States,>50K
32541,NaN,HS-grad,Separated,NaN,Not-in-family,Black,Female,United-States,<=50K
32542,NaN,HS-grad,Married-civ-spouse,NaN,Husband,White,Male,United-States,<=50K

In [6]:
obj_df.dropna()
obj_df.head

<bound method DataFrame.head of                workclass      education         marriage_status  \
0              State-gov      Bachelors           Never-married
1       Self-emp-not-inc      Bachelors      Married-civ-spouse
2                Private        HS-grad                Divorced
3                Private           11th      Married-civ-spouse
4                Private      Bachelors      Married-civ-spouse
5                Private        Masters      Married-civ-spouse
6                Private            9th   Married-spouse-absent
7       Self-emp-not-inc        HS-grad      Married-civ-spouse
8                Private        Masters           Never-married
9                Private      Bachelors      Married-civ-spouse
10               Private   Some-college      Married-civ-spouse
11             State-gov      Bachelors      Married-civ-spouse
12               Private      Bachelors           Never-married
13               Private     Assoc-acdm           Never-married
14               Private      Assoc-voc      Married-civ-spouse
15               Private        7th-8th      Married-civ-spouse
16      Self-emp-not-inc        HS-grad           Never-married
17               Private        HS-grad           Never-married
18               Private           11th      Married-civ-spouse
19      Self-emp-not-inc        Masters                Divorced
20               Private      Doctorate      Married-civ-spouse
21               Private        HS-grad               Separated
22           Federal-gov            9th      Married-civ-spouse
23               Private           11th      Married-civ-spouse
24               Private        HS-grad                Divorced
25             Local-gov      Bachelors      Married-civ-spouse
26               Private        HS-grad           Never-married
27                   NaN   Some-college      Married-civ-spouse
28               Private        HS-grad                Divorced
29               Private        HS-grad      Married-civ-spouse
...                  ...            ...                     ...
32531                NaN      Bachelors           Never-married
32532            Private      Doctorate      Married-civ-spouse
32533            Private      Bachelors      Married-civ-spouse
32534            Private   Some-college                Divorced
32535            Private           12th           Never-married
32536            Private      Bachelors           Never-married
32537            Private        HS-grad           Never-married
32538            Private      Bachelors                Divorced
32539                NaN      Doctorate      Married-civ-spouse
32540          State-gov        HS-grad               Separated
32541                NaN        HS-grad               Separated
32542                NaN        HS-grad      Married-civ-spouse
32543          Local-gov     Assoc-acdm                Divorced
32544            Private        Masters                Divorced
32545          Local-gov     Assoc-acdm      Married-civ-spouse
32546            Private     Assoc-acdm                Divorced
32547            Private        HS-grad      Married-civ-spouse
32548   Self-emp-not-inc    Prof-school           Never-married
32549          State-gov   Some-college                Divorced
32550   Self-emp-not-inc   Some-college      Married-civ-spouse
32551            Private           10th      Married-civ-spouse
32552            Private      Assoc-voc      Married-civ-spouse
32553            Private        Masters           Never-married
32554            Private        Masters      Married-civ-spouse
32555            Private   Some-college           Never-married
32556            Private     Assoc-acdm      Married-civ-spouse
32557            Private        HS-grad      Married-civ-spouse
32558            Private        HS-grad                 Widowed
32559            Private        HS-grad           Never-married
32560       Self-emp-inc        HS-grad      Married-civ-spouse

               occupation     relationship                 race      sex  \
0            Adm-clerical    Not-in-family                White     Male
1         Exec-managerial          Husband                White     Male
2       Handlers-cleaners    Not-in-family                White     Male
3       Handlers-cleaners          Husband                Black     Male
4          Prof-specialty             Wife                Black   Female
5         Exec-managerial             Wife                White   Female
6           Other-service    Not-in-family                Black   Female
7         Exec-managerial          Husband                White     Male
8          Prof-specialty    Not-in-family                White   Female
9         Exec-managerial          Husband                White     Male
10        Exec-managerial          Husband                Black     Male
11         Prof-specialty          Husband   Asian-Pac-Islander     Male
12           Adm-clerical        Own-child                White   Female
13                  Sales    Not-in-family                Black     Male
14           Craft-repair          Husband   Asian-Pac-Islander     Male
15       Transport-moving          Husband   Amer-Indian-Eskimo     Male
16        Farming-fishing        Own-child                White     Male
17      Machine-op-inspct        Unmarried                White     Male
18                  Sales          Husband                White     Male
19        Exec-managerial        Unmarried                White   Female
20         Prof-specialty          Husband                White     Male
21          Other-service        Unmarried                Black   Female
22        Farming-fishing          Husband                Black     Male
23       Transport-moving          Husband                White     Male
24           Tech-support        Unmarried                White   Female
25           Tech-support          Husband                White     Male
26           Craft-repair        Own-child                White     Male
27                    NaN          Husband   Asian-Pac-Islander     Male
28        Exec-managerial    Not-in-family                White     Male
29           Craft-repair          Husband                White     Male
...                   ...              ...                  ...      ...
32531                 NaN    Not-in-family   Asian-Pac-Islander   Female
32532      Prof-specialty          Husband                White     Male
32533     Exec-managerial          Husband   Asian-Pac-Islander     Male
32534        Adm-clerical        Unmarried                White   Female
32535     Protective-serv        Own-child                Black     Male
32536     Exec-managerial    Not-in-family                White   Female
32537        Craft-repair    Not-in-family                Black     Male
32538      Prof-specialty        Unmarried                Black   Female
32539                 NaN          Husband                White     Male
32540        Adm-clerical        Own-child                White   Female
32541                 NaN    Not-in-family                Black   Female
32542                 NaN          Husband                White     Male
32543      Prof-specialty        Unmarried                White   Female
32544       Other-service    Not-in-family                Other   Female
32545        Adm-clerical             Wife                White   Female
32546        Tech-support    Not-in-family                White   Female
32547   Machine-op-inspct          Husband                White     Male
32548      Prof-specialty    Not-in-family                White     Male
32549        Adm-clerical   Other-relative                White   Female
32550        Craft-repair          Husband                White     Male
32551   Handlers-cleaners          Husband   Amer-Indian-Eskimo     Male
32552               Sales          Husband                White     Male
32553        Tech-support    Not-in-family   Asian-Pac-Islander     Male
32554     Exec-managerial          Husband                White     Male
32555     Protective-serv    Not-in-family                White     Male
32556        Tech-support             Wife                White   Female
32557   Machine-op-inspct          Husband                White     Male
32558        Adm-clerical        Unmarried                White   Female
32559        Adm-clerical        Own-child                White     Male
32560     Exec-managerial             Wife                White   Female

       native_country     >50
0       United-States   <=50K
1       United-States   <=50K
2       United-States   <=50K
3       United-States   <=50K
4                Cuba   <=50K
5       United-States   <=50K
6             Jamaica   <=50K
7       United-States    >50K
8       United-States    >50K
9       United-States    >50K
10      United-States    >50K
11              India    >50K
12      United-States   <=50K
13      United-States   <=50K
14                NaN    >50K
15             Mexico   <=50K
16      United-States   <=50K
17      United-States   <=50K
18      United-States   <=50K
19      United-States    >50K
20      United-States    >50K
21      United-States   <=50K
22      United-States   <=50K
23      United-States   <=50K
24      United-States   <=50K
25      United-States    >50K
26      United-States   <=50K
27              South    >50K
28      United-States   <=50K
29      United-States   <=50K
...               ...     ...
32531   United-States   <=50K
32532   United-States    >50K
32533           Japan    >50K
32534   United-States   <=50K
32535   United-States   <=50K
32536   United-States    >50K
32537   United-States   <=50K
32538   United-States    >50K
32539   United-States    >50K
32540   United-States   <=50K
32541   United-States   <=50K
32542   United-States   <=50K
32543   United-States   <=50K
32544   United-States   <=50K
32545   United-States    >50K
32546   United-States   <=50K
32547          Mexico   <=50K
32548   United-States   <=50K
32549   United-States   <=50K
32550   United-States   <=50K
32551   United-States   <=50K
32552   United-States   <=50K
32553          Taiwan   <=50K
32554   United-States    >50K
32555   United-States   <=50K
32556   United-States   <=50K
32557   United-States    >50K
32558   United-States   <=50K
32559   United-States   <=50K
32560   United-States    >50K

[32561 rows x 9 columns]>

In [ ]:
cleanup_nums = {">50":     {" <=50K": 0, " >50K": 1}}
obj_df.replace(cleanup_nums, inplace=True)
obj_df.head(20)

In [ ]:
obj_df = obj_df.drop('relationship', 1)
obj_df.dtypes

In [ ]:
cleanup_nums = {"education":     {" Bachelors": " Some-college", " 11th": "12k", " HS-grad": "12k", " Prof-school": "Some-college", "Assoc-acdm": "Some-college", "Assoc-voc": "Some-college", " 9th":"12k", " 7th-8th":"12k", " 12th":"12k"," Masters":"Grad","1st-4th": "12k", "10th": "12k", " Doctorate": "Grade"," 5th-6th":"12k", " Preschool":"12k"}}
obj_df.replace(cleanup_nums, inplace=True)

In [ ]:
obj_df.head(20)